=== grosheth/gysmo/src/config/schema/config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "text": { "type": "string" },
          "keyword": { "type": "string" },
          "icon": { "type": "string" },
          "text_color": { "type": "string" },
          "value_color": { "type": "string" },
          "icon_color": { "type": "string" },
          "value": { "type": "string" }
        },
        "required": ["text", "icon"],
        "oneOf": [{ "required": ["value"] }, { "required": ["keyword"] }]
      }
    },
    "ascii": {
      "type": "object",
      "properties": {
        "path": { "type": "string" },
        "colors": { "type": "string" },
        "enabled": { "type": "boolean" },
        "padding": { "type": "integer" },
        "position": {
          "type": "string",
          "enum": ["top", "bottom", "left", "right"]
        }
      },
      "required": ["path", "enabled", "position"]
    },
    "header": {
      "type": "object",
      "properties": {
        "text": { "type": "string" },
        "text_color": { "type": "string" },
        "line_color": { "type": "string" },
        "line": { "type": "boolean" },
        "enabled": { "type": "boolean" }
      },
      "required": ["enabled"]
    },
    "footer": {
      "type": "object",
      "properties": {
        "text": { "type": "string" },
        "text_color": { "type": "string" },
        "line_color": { "type": "string" },
        "line": { "type": "boolean" },
        "enabled": { "type": "boolean" }
      },
      "required": ["enabled"]
    },
    "general": {
      "type": "object",
      "properties": {
        "padding": { "type": "integer" },
        "menu_type": {
          "type": "string",
          "enum": ["box", "list"]
        },
        "columns": { "type": "boolean" }
      },
      "required": ["menu_type"]
    }
  },
  "required": ["items", "ascii", "header", "footer", "general"]
}

=== grosheth/gysmo/src/config/config2.json
{
  "items": [
    {
      "text": "user",
      "keyword": "user",
      "icon": "",
      "value_color": "red",
      "text_color": "",
      "icon_color": "red"
    },
    {
      "text": "shell",
      "keyword": "shell",
      "icon": "",
      "value_color": "yellow",
      "text_color": "",
      "icon_color": "yellow",
      "value": "zsh"
    },
    {
      "text": "Distro",
      "keyword": "os_pretty_name",
      "icon": "󰌢",
      "value_color": "green",
      "text_color": "",
      "icon_color": "green"
    },
    {
      "text": "dm",
      "keyword": "dm",
      "icon": "󰏘",
      "value_color": "blue",
      "text_color": "",
      "icon_color": "blue"
    },
    {
      "text": "uptime",
      "keyword": "uptime",
      "icon": "",
      "value_color": "cyan",
      "text_color": "",
      "icon_color": "cyan"
    },
    {
      "text": "gpu",
      "keyword": "gpu",
      "icon": "",
      "value_color": "purple",
      "text_color": "",
      "icon_color": "purple"
    },
    {
      "text": "gpu usage",
      "keyword": "gpu %",
      "icon": "",
      "value_color": "red",
      "text_color": "",
      "icon_color": "red"
    },
    {
      "text": "cpu",
      "keyword": "cpu",
      "icon": "",
      "value_color": "yellow",
      "text_color": "",
      "icon_color": "yellow"
    },
    {
      "text": "cpu %",
      "keyword": "cpu %",
      "icon": "",
      "value_color": "green",
      "text_color": "",
      "icon_color": "green"
    },
    {
      "text": "ram",
      "keyword": "ram",
      "icon": "",
      "value_color": "blue",
      "text_color": "",
      "icon_color": "blue"
    },
    {
      "text": "ram %",
      "keyword": "ram %",
      "icon": "",
      "value_color": "cyan",
      "text_color": "",
      "icon_color": "cyan"
    },
    {
      "text": "drive",
      "keyword": "drive",
      "icon": "",
      "value_color": "purple",
      "text_color": "",
      "icon_color": "purple"
    },
    {
      "text": "drive %",
      "keyword": "drive %",
      "icon": "",
      "value_color": "red",
      "text_color": "",
      "icon_color": "red"
    },
    {
      "text": "terminal",
      "keyword": "term",
      "icon": "",
      "value_color": "yellow",
      "text_color": "",
      "icon_color": "yellow"
    },
    {
      "text": "version",
      "keyword": "os_version",
      "icon": "",
      "value_color": "green",
      "text_color": "",
      "icon_color": "green"
    },
    {
      "text": "public ip",
      "keyword": "public ip",
      "icon": "",
      "value_color": "blue",
      "text_color": "",
      "icon_color": "blue"
    },
    {
      "text": "processes",
      "keyword": "processes",
      "icon": "",
      "value_color": "blue",
      "text_color": "",
      "icon_color": "blue"
    },
    {
      "text": "wm",
      "keyword": "wm",
      "icon": "",
      "value_color": "cyan",
      "text_color": "",
      "icon_color": "cyan"
    },
    {
      "text": "kernel",
      "keyword": "kernel",
      "icon": "󰻀",
      "value_color": "green",
      "text_color": "",
      "icon_color": "green"
    },
    {
      "text": "host",
      "keyword": "hostname",
      "icon": "",
      "value_color": "blue",
      "text_color": "#FFFFFF",
      "icon_color": "blue",
      "value": "nixos"
    }
  ],
  "ascii": {
    "path": "ascii/gysmo2",
    "colors": "",
    "enabled": true,
    "horizontal_padding": 0,
    "vertical_padding": 0,
    "position": "left"
  },
  "header": {
    "enabled": false,
    "text": "NixOS",
    "text_color": "white",
    "line": false,
    "line_color": "red"
  },
  "footer": {
    "enabled": false,
    "text": "gysmo2",
    "text_color": "white",
    "line": true,
    "line_color": "red"
  },
  "general": {
    "menu_type": "box",
    "columns": false
  }
}

=== grosheth/gysmo/extras/github-stats/output.json
{
  "items": [
    
    {
      "text": "Python",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "62081 bytes (2.17%)"
    },
    
    {
      "text": "Go",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "9139 bytes (0.32%)"
    },
    
    {
      "text": "Rust",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "5433 bytes (0.19%)"
    },
    
    {
      "text": "Nix",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "2303621 bytes (80.58%)"
    },
    
    {
      "text": "JavaScript",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "4762 bytes (0.17%)"
    },
    
    {
      "text": "Shell",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "92723 bytes (3.24%)"
    },
    
    {
      "text": "Ruby",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "6782 bytes (0.24%)"
    },
    
    {
      "text": "HTML",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "1238 bytes (0.04%)"
    },
    
    {
      "text": "Perl",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "1236 bytes (0.04%)"
    },
    
    {
      "text": "CSS",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "11263 bytes (0.39%)"
    },
    
    {
      "text": "Makefile",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "471 bytes (0.02%)"
    },
    
    {
      "text": "Lua",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "305293 bytes (10.68%)"
    },
    
    {
      "text": "Nu",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "141 bytes (0.00%)"
    },
    
    {
      "text": "Nushell",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "136 bytes (0.00%)"
    },
    
    {
      "text": "Sage",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "14 bytes (0.00%)"
    },
    
    {
      "text": "Vim Script",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "51161 bytes (1.79%)"
    },
    
    {
      "text": "C",
      "keyword": "",
      "icon": "",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "3288 bytes (0.12%)"
    }
    
  ],
  "ascii": {
    "path": "ascii/github",
    "colors": "",
    "enabled": true,
    "horizontal_padding": 0,
    "vertical_padding": 10,
    "position": "left"
  },
  "header": {
    "enabled": false,
    "text": "",
    "text_color": "",
    "line": true,
    "line_color": ""
  },
  "footer": {
    "enabled": false,
    "text": "",
    "text_color": "",
    "line": true,
    "line_color": ""
  },
  "general": {
    "menu_type": "list",
    "columns": true
  }
}

=== grosheth/gysmo/src/config/config.json
{
  "items": [
    {
      "text": "user",
      "keyword": "user",
      "icon": "",
      "value_color": "red",
      "text_color": "",
      "icon_color": "red",
      "value": "My user"
    },
    {
      "text": "cpu",
      "keyword": "cpu",
      "icon": "",
      "value_color": "yellow",
      "text_color": "",
      "icon_color": "yellow"
    },
    {
      "text": "cpu",
      "keyword": "cpu %",
      "icon": "",
      "value_color": "yellow",
      "text_color": "",
      "icon_color": "yellow"
    }
  ],
  "ascii": {
    "path": "ascii/gysmo",
    "colors": "",
    "enabled": true,
    "horizontal_padding": 0,
    "vertical_padding": 0,
    "position": "left"
  },
  "header": {
    "enabled": true,
    "text": "NixOS",
    "text_color": "purple",
    "line": true,
    "line_color": ""
  },
  "footer": {
    "enabled": true,
    "text": "gysmo",
    "text_color": "blue",
    "line": true,
    "line_color": ""
  },
  "general": {
    "menu_type": "box",
    "columns": false
  }
}

=== grosheth/gysmo/extras/weather/config.json
{
    "items": [
        {
            "text": "Time",
            "icon": "\udb85\udc46",
            "value_color": "",
            "text_color": "",
            "icon_color": "",
            "value": "2025-03-05T19:30"
        },
        {
            "text": "Temperature",
            "icon": "\udb81\udd04",
            "value_color": "",
            "text_color": "",
            "icon_color": "cyan",
            "value": "4.9"
        },
        {
            "text": "Wind Speed",
            "icon": "\ue27e",
            "value_color": "",
            "text_color": "",
            "icon_color": "",
            "value": "30.2"
        },
        {
            "text": "Outside it is:",
            "icon": "\udb83\udf30",
            "value_color": "",
            "text_color": "",
            "icon_color": "blue",
            "value": "drizzle"
        }
    ],
    "ascii": {
        "path": "ascii/drizzle",
        "colors": "",
        "enabled": true,
        "horizontal_padding": 0,
        "vertical_padding": 0,
        "position": "left"
    },
    "header": {
        "enabled": true,
        "text": "Today's Weather",
        "text_color": "green",
        "line": true,
        "line_color": ""
    },
    "footer": {
        "enabled": false,
        "text": "",
        "text_color": "",
        "line": true,
        "line_color": ""
    },
    "general": {
        "menu_type": "box",
        "columns": false
    }
}

=== grosheth/gysmo/src/config/config-weather.json
{
  "items": [
    {
      "text": "Time",
      "keyword": "",
      "icon": "\udb85\udc46",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "2025-02-10T14:30"
    },
    {
      "text": "Temperature",
      "keyword": "",
      "icon": "\udb81\udd04",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "-8.6"
    },
    {
      "text": "Wind Speed",
      "keyword": "",
      "icon": "\ue27e",
      "value_color": "",
      "text_color": "",
      "icon_color": "",
      "value": "18.2"
    },
    {
      "text": "Outside it is:",
      "keyword": "",
      "icon": "\udb83\udf30",
      "value_color": "yellow",
      "text_color": "",
      "icon_color": "",
      "value": "mainly clear"
    }
  ],
  "ascii": {
    "path": "ascii/mainly clear",
    "colors": "yellow",
    "enabled": true,
    "horizontal_padding": 0,
    "vertical_padding": 0,
    "position": "top"
  },
  "header": {
    "enabled": true,
    "text": "Today's Weather",
    "text_color": "white",
    "line": true,
    "line_color": ""
  },
  "footer": {
    "enabled": false,
    "text": "",
    "text_color": "",
    "line": true,
    "line_color": ""
  },
  "general": {
    "menu_type": "box",
    "columns": false
  }
}

=== grosheth/gysmo/gysmo/config/config-full.json
{
  "items": [
    {
      "text": "OS ANSI Color",
      "keyword": "os_ansi_color",
      "icon": "",
      "text_color": "",
      "value_color": "green",
      "icon_color": "blue"
    },
    {
      "text": "OS Pretty Name",
      "keyword": "os_pretty_name",
      "icon": "",
      "text_color": "",
      "value_color": "blue",
      "icon_color": "cyan"
    },
    {
      "text": "OS Bug Report URL",
      "keyword": "os_bug_report_url",
      "icon": "",
      "text_color": "",
      "value_color": "white",
      "icon_color": "red"
    },
    {
      "text": "OS Build ID",
      "keyword": "os_build_id",
      "icon": "",
      "text_color": "",
      "value_color": "yellow",
      "icon_color": "blue"
    },
    {
      "text": "OS CPE Name",
      "keyword": "os_cpe_name",
      "icon": "",
      "text_color": "",
      "value_color": "purple",
      "icon_color": "green"
    },
    {
      "text": "OS Default Hostname",
      "keyword": "os_default_hostname",
      "icon": "",
      "text_color": "",
      "value_color": "red",
      "icon_color": "yellow"
    },
    {
      "text": "OS Documentation URL",
      "keyword": "os_documentation_url",
      "icon": "",
      "text_color": "",
      "value_color": "cyan",
      "icon_color": "purple"
    },
    {
      "text": "OS Home URL",
      "keyword": "os_home_url",
      "icon": "",
      "text_color": "",
      "value_color": "green",
      "icon_color": "blue"
    },
    {
      "text": "OS ID",
      "keyword": "os_id",
      "icon": "",
      "text_color": "",
      "value_color": "blue",
      "icon_color": "cyan"
    },
    {
      "text": "OS ID Like",
      "keyword": "os_id_like",
      "icon": "",
      "text_color": "",
      "value_color": "white",
      "icon_color": "red"
    },
    {
      "text": "OS Image ID",
      "keyword": "os_image_id",
      "icon": "",
      "text_color": "",
      "value_color": "yellow",
      "icon_color": "blue"
    },
    {
      "text": "OS Image Version",
      "keyword": "os_image_version",
      "icon": "",
      "text_color": "",
      "value_color": "purple",
      "icon_color": "green"
    },
    {
      "text": "OS Version",
      "keyword": "os_version",
      "icon": "",
      "text_color": "",
      "value_color": "red",
      "icon_color": "yellow"
    },
    {
      "text": "OS Logo",
      "keyword": "os_logo",
      "icon": "",
      "text_color": "",
      "value_color": "cyan",
      "icon_color": "purple"
    },
    {
      "text": "OS Name",
      "keyword": "os_name",
      "icon": "",
      "text_color": "",
      "value_color": "green",
      "icon_color": "blue"
    },
    {
      "text": "OS Support URL",
      "keyword": "os_support_url",
      "icon": "",
      "text_color": "",
      "value_color": "blue",
      "icon_color": "cyan"
    },
    {
      "text": "OS Variant",
      "keyword": "os_variant",
      "icon": "",
      "text_color": "",
      "value_color": "white",
      "icon_color": "red"
    },
    {
      "text": "OS Variant ID",
      "keyword": "os_variant_id",
      "icon": "",
      "text_color": "",
      "value_color": "yellow",
      "icon_color": "blue"
    },
    {
      "text": "OS Vendor Name",
      "keyword": "os_vendor_name",
      "icon": "",
      "text_color": "",
      "value_color": "purple",
      "icon_color": "green"
    },
    {
      "text": "OS Vendor URL",
      "keyword": "os_vendor_url",
      "icon": "",
      "text_color": "",
      "value_color": "red",
      "icon_color": "yellow"
    },
    {
      "text": "OS Version Codename",
      "keyword": "os_version_codename",
      "icon": "",
      "text_color": "",
      "value_color": "cyan",
      "icon_color": "purple"
    },
    {
      "text": "OS Version ID",
      "keyword": "os_version_id",
      "icon": "",
      "text_color": "",
      "value_color": "green",
      "icon_color": "blue"
    },
    {
      "text": "User",
      "keyword": "user",
      "icon": "",
      "text_color": "",
      "value_color": "blue",
      "icon_color": "cyan"
    },
    {
      "text": "Hostname",
      "keyword": "hostname",
      "icon": "",
      "text_color": "",
      "value_color": "white",
      "icon_color": "red"
    },
    {
      "text": "Kernel",
      "keyword": "kernel",
      "icon": "",
      "text_color": "",
      "value_color": "yellow",
      "icon_color": "blue"
    },
    {
      "text": "Shell",
      "keyword": "shell",
      "icon": "",
      "text_color": "",
      "value_color": "purple",
      "icon_color": "green"
    },
    {
      "text": "Uptime",
      "keyword": "uptime",
      "icon": "",
      "text_color": "",
      "value_color": "red",
      "icon_color": "yellow"
    },
    {
      "text": "Desktop Manager",
      "keyword": "dm",
      "icon": "",
      "text_color": "",
      "value_color": "cyan",
      "icon_color": "purple"
    },
    {
      "text": "GPU",
      "keyword": "gpu",
      "icon": "",
      "text_color": "",
      "value_color": "green",
      "icon_color": "blue"
    },
    {
      "text": "CPU",
      "keyword": "cpu",
      "icon": "",
      "text_color": "",
      "value_color": "blue",
      "icon_color": "cyan"
    },
    {
      "text": "RAM",
      "keyword": "ram",
      "icon": "",
      "text_color": "",
      "value_color": "white",
      "icon_color": "red"
    },
    {
      "text": "Drive",
      "keyword": "drive",
      "icon": "",
      "text_color": "",
      "value_color": "yellow",
      "icon_color": "blue"
    },
    {
      "text": "GPU Usage",
      "keyword": "gpu %",
      "icon": "",
      "text_color": "",
      "value_color": "purple",
      "icon_color": "green"
    },
    {
      "text": "CPU Usage",
      "keyword": "cpu %",
      "icon": "",
      "text_color": "",
      "value_color": "red",
      "icon_color": "yellow"
    },
    {
      "text": "RAM Usage",
      "keyword": "ram %",
      "icon": "",
      "text_color": "",
      "value_color": "cyan",
      "icon_color": "purple"
    },
    {
      "text": "Drive Usage",
      "keyword": "drive %",
      "icon": "",
      "text_color": "",
      "value_color": "green",
      "icon_color": "blue"
    },
    {
      "text": "Terminal",
      "keyword": "term",
      "icon": "",
      "text_color": "",
      "value_color": "blue",
      "icon_color": "cyan"
    },
    {
      "text": "Processes",
      "keyword": "processes",
      "icon": "",
      "text_color": "",
      "value_color": "white",
      "icon_color": "red"
    },
    {
      "text": "Window Manager",
      "keyword": "wm",
      "icon": "",
      "text_color": "",
      "value_color": "yellow",
      "icon_color": "blue"
    },
    {
      "text": "IP Address",
      "icon": "",
      "text_color": "",
      "value_color": "purple",
      "icon_color": "green",
      "value": "hidden"
    },
    {
      "text": "Public IP Address",
      "icon": "",
      "text_color": "",
      "value_color": "red",
      "icon_color": "yellow",
      "value": "hidden"
    },
    {
      "text": "Resolution",
      "keyword": "resolution",
      "icon": "",
      "text_color": "",
      "value_color": "cyan",
      "icon_color": "purple"
    }
  ],
  "ascii": {
    "path": "gysmo2",
    "colors": "",
    "enabled": true,
    "horizontal_padding": 20,
    "vertical_padding": 0,
    "position": "top"
  },
  "header": {
    "text": "",
    "text_color": "",
    "line_color": "red",
    "line": true,
    "enabled": false
  },
  "footer": {
    "text": "Footer",
    "text_color": "",
    "line_color": "red",
    "line": true,
    "enabled": false
  },
  "general": {
    "menu_type": "list",
    "columns": true
  }
}
